// ─── Enums ───────────────────────────────────────────────────────────────────

export const CUSTOMER_TYPES = [
  "EXPORT",
  "MERCHANT_EXPORTER",
  "MANUFACTURER",
  "PCD",
  "DOMESTIC",
] as const;
export type CustomerType = (typeof CUSTOMER_TYPES)[number];

export const CUSTOMER_TYPE_LABELS: Record<CustomerType, string> = {
  EXPORT: "Export",
  MERCHANT_EXPORTER: "Merchant Exporter",
  MANUFACTURER: "Manufacturer",
  PCD: "PCD",
  DOMESTIC: "Domestic",
};

export const CLIENT_LEVELS = [
  "PLATINUM",
  "GOLD",
  "SILVER",
  "BRONZE",
  "NO_VIP",
] as const;
export type ClientLevel = (typeof CLIENT_LEVELS)[number];

export const CLIENT_LEVEL_LABELS: Record<ClientLevel, string> = {
  PLATINUM: "Platinum",
  GOLD: "Gold",
  SILVER: "Silver",
  BRONZE: "Bronze",
  NO_VIP: "Standard",
};

export const ADDRESS_TYPES = ["REGISTERED", "BILLING", "SHIPPING"] as const;
export type AddressType = (typeof ADDRESS_TYPES)[number];

export const ADDRESS_TYPE_LABELS: Record<AddressType, string> = {
  REGISTERED: "Registered",
  BILLING: "Billing",
  SHIPPING: "Shipping",
};

export const DOCUMENT_TYPES = [
  "DRUG_LICENSE",
  "WHOLESALE_LICENSE",
  "WHO_GMP_COPY",
  "STATE_GMP_GLP_COPY",
  "NEUTRAL_CODE_CERTIFICATE",
  "LIST_OF_INTERNATIONAL_ACCREDITATION",
  "MSME_CERTIFICATE",
  "FIRM_REGISTRATION_CERTIFICATE",
  "BANK_CHQ_LEAF",
  "IEC_CODE",
  "GST_RC_COPY",
  "PAN_CARD_COPY",
  "ADDRESS_PROOF_DOCS_COPY",
  "AADHAR_COPY",
  "CIN_COPY",
] as const;
export type DocumentType = (typeof DOCUMENT_TYPES)[number];

export const DOCUMENT_TYPE_LABELS: Record<DocumentType, string> = {
  DRUG_LICENSE: "Drug License",
  WHOLESALE_LICENSE: "Wholesale License",
  WHO_GMP_COPY: "WHO GMP Copy",
  STATE_GMP_GLP_COPY: "State GMP/GLP Copy",
  NEUTRAL_CODE_CERTIFICATE: "Neutral Code Certificate",
  LIST_OF_INTERNATIONAL_ACCREDITATION: "International Accreditation",
  MSME_CERTIFICATE: "MSME Certificate",
  FIRM_REGISTRATION_CERTIFICATE: "Firm Registration Certificate",
  BANK_CHQ_LEAF: "Bank Cheque Leaf",
  IEC_CODE: "IEC Code",
  GST_RC_COPY: "GST RC Copy",
  PAN_CARD_COPY: "PAN Card Copy",
  ADDRESS_PROOF_DOCS_COPY: "Address Proof Copy",
  AADHAR_COPY: "Aadhar Copy",
  CIN_COPY: "CIN Copy",
};

// ─── Sub-entities ────────────────────────────────────────────────────────────

export interface Address {
  id?: string;
  type: AddressType;
  line1: string;
  line2?: string;
  city: string;
  state: string;
  country: string;
  pinCode: string;
}

export interface PointOfContact {
  id?: string;
  personName: string;
  designation: string;
  department: string;
  phone: string;
  email: string;
  primary?: boolean;
}

export interface PaymentTerms {
  advancePercent?: number;
  beforeDispatchPercent?: number;
  afterDispatchDays?: number;
  afterDispatchPercent?: number;
}

export interface BankDetail {
  id?: string;
  accountHolderName: string;
  accountNumber: string;
  bankName: string;
  branchName: string;
  ifscCode: string;
  swiftCode?: string;
}

export interface ClientDocument {
  id?: string;
  documentType: DocumentType;
  fileUrl?: string;
}

// ─── Main entity ─────────────────────────────────────────────────────────────

export interface Client {
  id: string;
  customerCode: string;
  customerType: CustomerType;
  companyName: string;
  tradeName?: string;
  annualTurnover: number;
  clientLevel: ClientLevel;
  paymentTerms?: PaymentTerms;
  addresses: Address[];
  pointOfContacts: PointOfContact[];
  documents: ClientDocument[];
  bankDetail?: BankDetail;
}

// ─── DTOs ────────────────────────────────────────────────────────────────────

export interface ClientRequestDto {
  customerCode?: string; // auto-generated by backend
  customerType: CustomerType;
  companyName: string;
  tradeName?: string;
  annualTurnover?: number;
  paymentTerms?: PaymentTerms;
  addresses?: Address[];
  pointOfContacts?: PointOfContact[];
}
