import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useState, useEffect } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { motion } from "motion/react";
import {
  Building2,
  CheckCircle2,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Globe2,
  Loader2,
  Mail,
  MapPin,
  Phone,
  Plus,
  Search,
  Send,
  Trash2,
  Upload,
  Users,
  Pencil,
  Crown,
  Award,
  Medal,
  Shield,
  Star,
} from "lucide-react";
import { toast } from "sonner";

import { PageHeader, Panel, Reveal, StatusChip, EmptyState } from "@/components/kit";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { DocumentViewerDialog } from "@/components/document-viewer-dialog";
import { PaginationBar } from "@/components/ui/pagination-bar";

import {
  fetchClients,
  createClient,
  updateClient,
  resendRegistrationEmail,
  uploadDocument,
  deleteDocument,
  getDocumentDownloadUrl,
} from "@/lib/client-api";
import type {
  Client,
  ClientRequestDto,
  Address,
  CustomerType,
  ClientLevel,
  DocumentType,
  ClientDocument,
} from "@/lib/client-types";
import {
  CUSTOMER_TYPES,
  CUSTOMER_TYPE_LABELS,
  CLIENT_LEVEL_LABELS,
  ADDRESS_TYPE_LABELS,
  DOCUMENT_TYPE_LABELS,
  DOCUMENT_TYPES,
} from "@/lib/client-types";

// ─── Route ───────────────────────────────────────────────────────────────────

export const Route = createFileRoute("/_shell/clients")({
  head: () => ({
    meta: [
      { title: "Clients · NCOP ERP" },
      {
        name: "description",
        content:
          "Company records, contacts, payment terms, banking details and document dossiers for every pharmaceutical partner.",
      },
    ],
  }),
  component: ClientMaster,
});

// ─── Constants ───────────────────────────────────────────────────────────────

const filterSegments = ["All", ...CUSTOMER_TYPES] as const;

const TIER_CONFIG: Record<ClientLevel, { icon: typeof Crown; color: string }> = {
  PLATINUM: { icon: Crown, color: "bg-violet-500/12 text-violet-600 border-violet-500/25" },
  GOLD: { icon: Award, color: "bg-amber-500/12 text-amber-600 border-amber-500/25" },
  SILVER: { icon: Medal, color: "bg-slate-400/12 text-slate-500 border-slate-400/25" },
  BRONZE: { icon: Shield, color: "bg-orange-500/12 text-orange-600 border-orange-500/25" },
  NO_VIP: { icon: Star, color: "bg-muted text-muted-foreground border-border" },
};

// ─── Address field type ──────────────────────────────────────────────────────

interface AddressFields {
  line1: string;
  line2: string;
  city: string;
  state: string;
  country: string;
  pinCode: string;
}

const emptyAddress: AddressFields = {
  line1: "",
  line2: "",
  city: "",
  state: "",
  country: "",
  pinCode: "",
};

// ─── Form types ──────────────────────────────────────────────────────────────

interface ClientFormValues {
  // customerCode is auto-generated by the backend
  customerType: CustomerType;
  companyName: string;
  tradeName: string;
  annualTurnover: string;
  paymentTerms: {
    advancePercent: string;
    beforeDispatchPercent: string;
    afterDispatchDays: string;
    afterDispatchPercent: string;
  };
  // Fixed address blocks
  registeredAddress: AddressFields;
  billingAddress: AddressFields;
  shippingAddress: AddressFields;
  billingSameAsRegistered: boolean;
  shippingSameAsBilling: boolean;
  // Dynamic POC list
  pointOfContacts: {
    personName: string;
    designation: string;
    department: string;
    phone: string;
    email: string;
    primary: boolean;
  }[];
}

const defaultFormValues: ClientFormValues = {
  customerType: "DOMESTIC",
  companyName: "",
  tradeName: "",
  annualTurnover: "",
  paymentTerms: {
    advancePercent: "",
    beforeDispatchPercent: "",
    afterDispatchDays: "",
    afterDispatchPercent: "",
  },
  registeredAddress: { ...emptyAddress },
  billingAddress: { ...emptyAddress },
  shippingAddress: { ...emptyAddress },
  billingSameAsRegistered: false,
  shippingSameAsBilling: false,
  pointOfContacts: [],
};

function buildAddressArray(values: ClientFormValues): Address[] {
  const addresses: Address[] = [];

  const reg = values.registeredAddress;
  if (reg.line1) {
    addresses.push({ type: "REGISTERED", ...reg });
  }

  if (values.billingSameAsRegistered && reg.line1) {
    addresses.push({ type: "BILLING", ...reg });
  } else if (values.billingAddress.line1) {
    addresses.push({ type: "BILLING", ...values.billingAddress });
  }

  const billingSource = values.billingSameAsRegistered ? reg : values.billingAddress;
  if (values.shippingSameAsBilling && billingSource.line1) {
    addresses.push({ type: "SHIPPING", ...billingSource });
  } else if (values.shippingAddress.line1) {
    addresses.push({ type: "SHIPPING", ...values.shippingAddress });
  }

  return addresses;
}

function formToDto(values: ClientFormValues): ClientRequestDto {
  const addresses = buildAddressArray(values);
  return {
    customerCode: "", // auto-generated by backend, ignored
    customerType: values.customerType,
    companyName: values.companyName,
    tradeName: values.tradeName || undefined,
    annualTurnover: values.annualTurnover ? Number(values.annualTurnover) : undefined,
    paymentTerms: {
      advancePercent: values.paymentTerms.advancePercent
        ? Number(values.paymentTerms.advancePercent)
        : undefined,
      beforeDispatchPercent: values.paymentTerms.beforeDispatchPercent
        ? Number(values.paymentTerms.beforeDispatchPercent)
        : undefined,
      afterDispatchDays: values.paymentTerms.afterDispatchDays
        ? Number(values.paymentTerms.afterDispatchDays)
        : undefined,
      afterDispatchPercent: values.paymentTerms.afterDispatchPercent
        ? Number(values.paymentTerms.afterDispatchPercent)
        : undefined,
    },
    addresses: addresses.length > 0 ? addresses : undefined,
    pointOfContacts: values.pointOfContacts.length > 0 ? values.pointOfContacts : undefined,
  };
}

function areAddressesEqual(a?: AddressFields, b?: AddressFields): boolean {
  if (!a || !b) return false;
  if (!a.line1?.trim() && !a.city?.trim()) return false;
  return (
    (a.line1 ?? "").trim().toLowerCase() === (b.line1 ?? "").trim().toLowerCase() &&
    (a.line2 ?? "").trim().toLowerCase() === (b.line2 ?? "").trim().toLowerCase() &&
    (a.city ?? "").trim().toLowerCase() === (b.city ?? "").trim().toLowerCase() &&
    (a.state ?? "").trim().toLowerCase() === (b.state ?? "").trim().toLowerCase() &&
    (a.country ?? "").trim().toLowerCase() === (b.country ?? "").trim().toLowerCase() &&
    (a.pinCode ?? "").trim().toLowerCase() === (b.pinCode ?? "").trim().toLowerCase()
  );
}

function clientToFormValues(client: Client): ClientFormValues {
  const registeredAddr = client.addresses?.find((a) => a.type === "REGISTERED");
  const billingAddr = client.addresses?.find((a) => a.type === "BILLING");
  const shippingAddr = client.addresses?.find((a) => a.type === "SHIPPING");

  const toFields = (a?: Address): AddressFields => ({
    line1: a?.line1 ?? "",
    line2: a?.line2 ?? "",
    city: a?.city ?? "",
    state: a?.state ?? "",
    country: a?.country ?? "",
    pinCode: a?.pinCode ?? "",
  });

  const regFields = toFields(registeredAddr);
  const billFields = toFields(billingAddr);
  const shipFields = toFields(shippingAddr);

  // Detect if billing was same as registered
  const billingSameAsRegistered =
    !!registeredAddr && !!billingAddr && areAddressesEqual(regFields, billFields);

  const billingSource = billingSameAsRegistered ? regFields : billFields;

  // Detect if shipping was same as billing
  const shippingSameAsBilling =
    (!!billingAddr || billingSameAsRegistered) &&
    !!shippingAddr &&
    areAddressesEqual(billingSource, shipFields);

  return {
    customerType: client.customerType,
    companyName: client.companyName,
    tradeName: client.tradeName ?? "",
    annualTurnover: client.annualTurnover?.toString() ?? "",
    paymentTerms: {
      advancePercent: client.paymentTerms?.advancePercent?.toString() ?? "",
      beforeDispatchPercent: client.paymentTerms?.beforeDispatchPercent?.toString() ?? "",
      afterDispatchDays: client.paymentTerms?.afterDispatchDays?.toString() ?? "",
      afterDispatchPercent: client.paymentTerms?.afterDispatchPercent?.toString() ?? "",
    },
    registeredAddress: regFields,
    billingAddress: billingSameAsRegistered ? { ...regFields } : billFields,
    shippingAddress: shippingSameAsBilling ? { ...billingSource } : shipFields,
    billingSameAsRegistered,
    shippingSameAsBilling,
    pointOfContacts: (client.pointOfContacts ?? []).map((p) => ({
      personName: p.personName,
      designation: p.designation,
      department: p.department,
      phone: p.phone,
      email: p.email,
      primary: p.primary ?? false,
    })),
  };
}

// ─── Tier Badge ──────────────────────────────────────────────────────────────

function TierBadge({ level }: { level: ClientLevel }) {
  const cfg = TIER_CONFIG[level];
  const Icon = cfg.icon;
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold whitespace-nowrap",
        cfg.color,
      )}
    >
      <Icon className="size-3" />
      {CLIENT_LEVEL_LABELS[level]}
    </span>
  );
}

// ─── Currency Formatter ──────────────────────────────────────────────────────

function formatINR(value: number): string {
  if (value >= 10_000_000) return `₹${(value / 10_000_000).toFixed(2)} Cr`;
  if (value >= 100_000) return `₹${(value / 100_000).toFixed(2)} L`;
  return `₹${value.toLocaleString("en-IN")}`;
}

// ─── Main Component ──────────────────────────────────────────────────────────

function ClientMaster() {
  const queryClient = useQueryClient();
  const [query, setQuery] = useState("");
  const [segment, setSegment] = useState<(typeof filterSegments)[number]>("All");
  const [activeId, setActiveId] = useState<string | null>(null);
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const [formOpen, setFormOpen] = useState(false);
  const [editingClient, setEditingClient] = useState<Client | null>(null);

  const {
    data: pageData,
    isLoading,
    isError,
    error,
  } = useQuery({
    queryKey: ["clients", page, pageSize, query],
    queryFn: () => fetchClients({ page, size: pageSize, search: query.trim() || undefined }),
    refetchInterval: 3000,
  });

  const clients = pageData?.content ?? [];
  const totalElements = pageData?.totalElements ?? 0;
  const totalPages = pageData?.totalPages ?? 1;

  const active = clients.find((c) => c.id === activeId) ?? null;

  const createMutation = useMutation({
    mutationFn: createClient,
    onSuccess: (newClient) => {
      queryClient.setQueryData<Client[]>(["clients"], (old = []) => [newClient, ...old]);
      queryClient.invalidateQueries({ queryKey: ["clients"] });
      setFormOpen(false);
      setActiveId(newClient.id);
      toast.success("Client created successfully");
    },
    onError: (err: Error) => toast.error(`Failed to create client: ${err.message}`),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, dto }: { id: string; dto: ClientRequestDto }) => updateClient(id, dto),
    onSuccess: (updatedClient) => {
      queryClient.setQueryData<Client[]>(["clients"], (old = []) =>
        old.map((c) => (c.id === updatedClient.id ? updatedClient : c))
      );
      queryClient.invalidateQueries({ queryKey: ["clients"] });
      setFormOpen(false);
      setEditingClient(null);
      toast.success("Client updated successfully");
    },
    onError: (err: Error) => toast.error(`Failed to update client: ${err.message}`),
  });

  const emailMutation = useMutation({
    mutationFn: resendRegistrationEmail,
    onSuccess: () => toast.success("Registration email sent"),
    onError: (err: Error) => toast.error(`Failed to send email: ${err.message}`),
  });

  const filtered = clients.filter(
    (c) =>
      (segment === "All" || c.customerType === segment) &&
      `${c.companyName} ${c.customerCode} ${c.tradeName ?? ""}`
        .toLowerCase()
        .includes(query.toLowerCase()),
  );

  const firstPoc = (c: Client) => c.pointOfContacts?.[0];
  const firstAddr = (c: Client) => c.addresses?.[0];

  function openEdit(client: Client) {
    setEditingClient(client);
    setFormOpen(true);
  }

  function openCreate() {
    setEditingClient(null);
    setFormOpen(true);
  }

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="ERP"
        title="Clients"
        description={
          isLoading
            ? "Loading clients…"
            : `${clients.length} registered partner${clients.length !== 1 ? "s" : ""}. Select a company to open its full dossier.`
        }
        actions={
          <>
            <Button variant="outline" onClick={() => toast("Client list exported as XLSX")}>
              <Download className="size-4" /> Export
            </Button>
            <Button onClick={openCreate}>
              <Plus className="size-4" /> Add client
            </Button>
          </>
        }
      />

      {/* ── Filters ── */}
      <Panel className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="relative w-full lg:max-w-sm">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={query}
            onChange={(e) => { setQuery(e.target.value); setPage(0); }}
            placeholder="Search by company, code or trade name…"
            className="pl-9"
          />
        </div>
        <div className="flex flex-wrap gap-1.5">
          {filterSegments.map((s) => (
            <button
              key={s}
              onClick={() => setSegment(s)}
              className={cn(
                "rounded-full border px-3 py-1.5 text-xs font-medium transition-colors",
                segment === s
                  ? "border-primary bg-primary/10 text-primary"
                  : "border-border text-muted-foreground hover:bg-secondary",
              )}
            >
              {s === "All" ? "All" : CUSTOMER_TYPE_LABELS[s as CustomerType]}
            </button>
          ))}
        </div>
      </Panel>

      {/* ── Loading ── */}
      {isLoading && (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <Panel key={i}>
              <div className="flex items-start gap-3">
                <Skeleton className="size-11 rounded-xl" />
                <div className="flex-1 space-y-2">
                  <Skeleton className="h-4 w-3/4" />
                  <Skeleton className="h-3 w-1/2" />
                </div>
              </div>
              <div className="mt-5 space-y-2">
                <Skeleton className="h-3 w-full" />
                <Skeleton className="h-3 w-2/3" />
              </div>
            </Panel>
          ))}
        </div>
      )}

      {/* ── Error ── */}
      {isError && (
        <EmptyState
          icon={<Users className="size-5" />}
          title="Failed to load clients"
          description={error?.message ?? "An unexpected error occurred."}
          action={
            <Button
              variant="outline"
              size="sm"
              onClick={() => queryClient.invalidateQueries({ queryKey: ["clients"] })}
            >
              Retry
            </Button>
          }
        />
      )}

      {/* ── Empty / No matches ── */}
      {!isLoading && !isError && filtered.length === 0 && (
        <EmptyState
          icon={<Users className="size-5" />}
          title={clients.length === 0 ? "No clients yet" : "No clients match your filters"}
          description={
            clients.length === 0
              ? "Add your first client to get started."
              : "Try a different segment or clear the search term."
          }
          action={
            clients.length === 0 ? (
              <Button size="sm" onClick={openCreate}>
                <Plus className="size-4" /> Add client
              </Button>
            ) : (
              <Button variant="outline" size="sm" onClick={() => { setQuery(""); setSegment("All"); }}>
                Reset filters
              </Button>
            )
          }
        />
      )}

      {/* ── Card Grid ── */}
      {!isLoading && !isError && filtered.length > 0 && (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {filtered.map((c, i) => {
            const poc = firstPoc(c);
            const addr = firstAddr(c);
            return (
              <Reveal key={c.id} delay={i * 0.05}>
                <button onClick={() => setActiveId(c.id)} className="w-full text-left h-full">
                  <Panel hover className="h-full">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-sm font-bold text-primary">
                          {c.companyName.slice(0, 2).toUpperCase()}
                        </span>
                        <div>
                          <p className="font-semibold leading-tight">{c.companyName}</p>
                          <p className="text-xs text-muted-foreground">
                            {c.customerCode} · {CUSTOMER_TYPE_LABELS[c.customerType]}
                          </p>
                        </div>
                      </div>
                      <TierBadge level={c.clientLevel} />
                    </div>

                    <dl className="mt-5 space-y-2 text-xs text-muted-foreground">
                      {addr && (
                        <div className="flex items-center gap-2">
                          <Globe2 className="size-3.5" /> {addr.city}, {addr.country}
                        </div>
                      )}
                      {poc && (
                        <div className="flex items-center gap-2">
                          <Mail className="size-3.5" /> {poc.email}
                        </div>
                      )}
                    </dl>

                    <div className="mt-5 flex items-center justify-between border-t border-border pt-4">
                      <div>
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Annual Turnover</p>
                        <p className="text-sm font-semibold tabular-nums">
                          {c.annualTurnover ? formatINR(c.annualTurnover) : "—"}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Documents</p>
                        <p className="text-sm font-semibold">{c.documents?.length ?? 0}</p>
                      </div>
                    </div>
                  </Panel>
                </button>
              </Reveal>
            );
          })}
        </div>
      )}

      {/* ── Detail Drawer ── */}
      <Sheet open={!!active} onOpenChange={(o) => !o && setActiveId(null)}>
        <SheetContent className="glass w-full overflow-y-auto sm:max-w-xl">
          {active && (
            <ClientDetailDrawer
              client={active}
              onEdit={openEdit}
              onResendEmail={(id) => emailMutation.mutate(id)}
            />
          )}
        </SheetContent>
      </Sheet>

      {/* ── Add / Edit Dialog ── */}
      <ClientFormDialog
        open={formOpen}
        onOpenChange={(o) => {
          if (!o) { setFormOpen(false); setEditingClient(null); }
        }}
        editingClient={editingClient}
        isSubmitting={createMutation.isPending || updateMutation.isPending}
        onSubmit={(values) => {
          const dto = formToDto(values);
          if (editingClient) {
            updateMutation.mutate({ id: editingClient.id, dto });
          } else {
            createMutation.mutate(dto);
          }
        }}
      />
    </div>
  );
}

// ─── Detail Drawer ───────────────────────────────────────────────────────────

function ClientDetailDrawer({
  client,
  onEdit,
  onResendEmail,
}: {
  client: Client;
  onEdit: (c: Client) => void;
  onResendEmail: (id: string) => void;
}) {
  const poc = client.pointOfContacts ?? [];
  const addresses = client.addresses ?? [];
  const documents = client.documents ?? [];

  return (
    <>
      <SheetHeader className="border-b border-border/60 pb-3">
        <div className="flex items-start justify-between gap-3 pt-6">
          <div className="flex items-center gap-3">
            <span className="grid size-12 place-items-center rounded-2xl bg-primary/10 text-base font-bold text-primary">
              {client.companyName.slice(0, 2).toUpperCase()}
            </span>
            <div className="space-y-1">
              <SheetTitle className="text-lg">{client.companyName}</SheetTitle>
              <div className="flex items-center gap-2">
                <TierBadge level={client.clientLevel} />
                <span className="text-xs text-muted-foreground">{client.customerCode}</span>
              </div>
            </div>
          </div>
          <div className="flex gap-1.5 pt-1">
            <Button variant="ghost" size="icon" className="size-8" onClick={() => onResendEmail(client.id)} title="Resend registration email">
              <Send className="size-4" />
            </Button>
            <Button variant="ghost" size="icon" className="size-8" onClick={() => onEdit(client)} title="Edit client">
              <Pencil className="size-4" />
            </Button>
          </div>
        </div>
      </SheetHeader>

      <div className="px-4 pb-8 pt-4">
        <Tabs defaultValue="overview">
          <TabsList className="w-full">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="commercial">Commercial</TabsTrigger>
            <TabsTrigger value="documents">Documents</TabsTrigger>
          </TabsList>

          {/* ── Overview ── */}
          <TabsContent value="overview" className="mt-5 space-y-5">
            <div className="surface p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Company details</p>
              <dl className="mt-3 space-y-2 text-sm">
                <div className="flex justify-between"><dt className="text-muted-foreground">Customer Type</dt><dd className="font-medium">{CUSTOMER_TYPE_LABELS[client.customerType]}</dd></div>
                {client.tradeName && <div className="flex justify-between"><dt className="text-muted-foreground">Trade Name</dt><dd className="font-medium">{client.tradeName}</dd></div>}
                <div className="flex justify-between"><dt className="text-muted-foreground">Annual Turnover</dt><dd className="font-medium">{client.annualTurnover ? formatINR(client.annualTurnover) : "—"}</dd></div>
                <div className="flex justify-between"><dt className="text-muted-foreground">Client Level</dt><dd><TierBadge level={client.clientLevel} /></dd></div>
              </dl>
            </div>

            {addresses.length > 0 && (
              <div className="space-y-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Addresses</p>
                {addresses.map((a, i) => (
                  <div key={a.id ?? i} className="surface p-4">
                    <StatusChip status={ADDRESS_TYPE_LABELS[a.type]} />
                    <p className="mt-2 flex items-start gap-2 text-sm">
                      <MapPin className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
                      {[a.line1, a.line2, a.city, a.state, a.pinCode, a.country].filter(Boolean).join(", ")}
                    </p>
                  </div>
                ))}
              </div>
            )}

            {poc.length > 0 && (
              <div className="space-y-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Points of Contact</p>
                {poc.map((p, i) => (
                  <div key={p.id ?? i} className="surface p-4">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-semibold">{p.personName}</p>
                      {p.primary && (
                        <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary">Primary</span>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground">{p.designation} · {p.department}</p>
                    <div className="mt-2 space-y-1 text-xs">
                      <p className="flex items-center gap-2"><Mail className="size-3.5 text-muted-foreground" /> {p.email}</p>
                      <p className="flex items-center gap-2"><Phone className="size-3.5 text-muted-foreground" /> {p.phone}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </TabsContent>

          {/* ── Commercial ── */}
          <TabsContent value="commercial" className="mt-5 space-y-5">
            {client.paymentTerms && (
              <div className="surface p-4">
                <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Payment Terms</p>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { l: "Advance %", v: client.paymentTerms.advancePercent },
                    { l: "Before Dispatch %", v: client.paymentTerms.beforeDispatchPercent },
                    { l: "After Dispatch Days", v: client.paymentTerms.afterDispatchDays },
                    { l: "After Dispatch %", v: client.paymentTerms.afterDispatchPercent },
                  ].map((f) => (
                    <div key={f.l}><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{f.l}</p><p className="mt-1 text-sm font-semibold">{f.v ?? "—"}</p></div>
                  ))}
                </div>
              </div>
            )}

            {client.bankDetail && (
              <div className="surface p-4">
                <p className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><Building2 className="size-3.5" /> Bank Details</p>
                <dl className="space-y-2 text-xs">
                  {[
                    ["Account Holder", client.bankDetail.accountHolderName],
                    ["Account No.", client.bankDetail.accountNumber],
                    ["Bank", client.bankDetail.bankName],
                    ["Branch", client.bankDetail.branchName],
                    ["IFSC", client.bankDetail.ifscCode],
                    ["SWIFT", client.bankDetail.swiftCode],
                  ].filter(([, v]) => v).map(([l, v]) => (
                    <div key={l} className="flex justify-between gap-4"><dt className="text-muted-foreground">{l}</dt><dd className="text-right font-medium">{v}</dd></div>
                  ))}
                </dl>
              </div>
            )}

            <div className="surface p-4">
              <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Client Tier</p>
              <div className="flex items-center gap-3">
                <TierBadge level={client.clientLevel} />
                <span className="text-xs text-muted-foreground">Based on ₹{((client.annualTurnover ?? 0) / 10_000_000).toFixed(2)} Cr annual turnover</span>
              </div>
            </div>
          </TabsContent>

          {/* ── Documents ── */}
          <TabsContent value="documents" className="mt-5">
            <AdminDocumentsPanel client={client} />
          </TabsContent>
        </Tabs>
      </div>
    </>
  );
}

// ─── Address Block Component ─────────────────────────────────────────────────

function AddressBlock({
  title,
  prefix,
  form,
  disabled,
  sameAsLabel,
  sameAsField,
  onSameAsChange,
  sameAsChecked,
}: {
  title: string;
  prefix: "registeredAddress" | "billingAddress" | "shippingAddress";
  form: ReturnType<typeof useForm<ClientFormValues>>;
  disabled?: boolean;
  sameAsLabel?: string;
  sameAsField?: string;
  onSameAsChange?: (checked: boolean) => void;
  sameAsChecked?: boolean;
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <p className="text-xs font-semibold text-muted-foreground">{title}</p>
        {sameAsLabel && (
          <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer">
            <Checkbox
              checked={sameAsChecked}
              onCheckedChange={(v) => onSameAsChange?.(v === true)}
            />
            {sameAsLabel}
          </label>
        )}
      </div>
      {!disabled && (
        <div className="space-y-3">
          <div className="space-y-1">
            <Label className="text-xs">Address Line 1</Label>
            <Input {...form.register(`${prefix}.line1`)} placeholder="Street address" />
          </div>
          <div className="space-y-1">
            <Label className="text-xs">Address Line 2</Label>
            <Input {...form.register(`${prefix}.line2`)} placeholder="Apt, suite, etc." />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="space-y-1">
              <Label className="text-xs">City</Label>
              <Input {...form.register(`${prefix}.city`)} placeholder="City" />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">State</Label>
              <Input {...form.register(`${prefix}.state`)} placeholder="State" />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">Pin Code</Label>
              <Input {...form.register(`${prefix}.pinCode`)} placeholder="Pin Code" />
            </div>
          </div>
          <div className="space-y-1">
            <Label className="text-xs">Country</Label>
            <Input {...form.register(`${prefix}.country`)} placeholder="Country" />
          </div>
        </div>
      )}
      {disabled && (
        <p className="text-xs italic text-muted-foreground">
          Using {sameAsLabel?.toLowerCase().replace("same as ", "")} address
        </p>
      )}
    </div>
  );
}

// ─── Add / Edit Form Dialog ──────────────────────────────────────────────────

function ClientFormDialog({
  open,
  onOpenChange,
  editingClient,
  isSubmitting,
  onSubmit,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  editingClient: Client | null;
  isSubmitting: boolean;
  onSubmit: (values: ClientFormValues) => void;
}) {
  const isEdit = !!editingClient;

  const form = useForm<ClientFormValues>({
    defaultValues: editingClient ? clientToFormValues(editingClient) : defaultFormValues,
  });

  // Reset form when the dialog opens with a different client
  useEffect(() => {
    if (open) {
      form.reset(editingClient ? clientToFormValues(editingClient) : defaultFormValues);
    }
  }, [open, editingClient?.id]);

  const billingSameAsRegistered = form.watch("billingSameAsRegistered");
  const shippingSameAsBilling = form.watch("shippingSameAsBilling");

  const {
    fields: pocFields,
    append: addPoc,
    remove: removePoc,
  } = useFieldArray({ control: form.control, name: "pointOfContacts" });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-sm:fixed max-sm:inset-0 max-sm:w-full max-sm:h-full max-sm:max-w-none max-sm:rounded-none max-sm:border-0 sm:w-[92vw] sm:max-w-3xl lg:max-w-4xl sm:h-[88vh] sm:rounded-2xl flex flex-col p-0 overflow-hidden shadow-2xl">
        {/* Fixed Header */}
        <DialogHeader className="px-6 py-4 shrink-0 border-b border-border/40 bg-muted/20">
          <DialogTitle className="text-lg font-semibold">{isEdit ? "Edit Client" : "Add New Client"}</DialogTitle>
          <DialogDescription className="text-xs text-muted-foreground">
            {isEdit
              ? `Editing ${editingClient?.companyName} (${editingClient?.customerCode})`
              : "Fill in the details below. Customer code will be auto-generated."}
          </DialogDescription>
        </DialogHeader>

        {/* Scrollable Form Body */}
        <div className="flex-1 min-h-0 overflow-y-auto px-6 py-5">
          <form id="client-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* ── Company Info ── */}
            <fieldset className="space-y-4">
              <legend className="text-sm font-semibold">Company Information</legend>

              {isEdit && (
                <div className="surface flex items-center gap-3 p-3 rounded-lg">
                  <span className="text-xs font-medium text-muted-foreground">Customer Code</span>
                  <span className="text-sm font-semibold">{editingClient?.customerCode}</span>
                  <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">Auto-generated</span>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="customerType">Customer Type *</Label>
                  <Select value={form.watch("customerType")} onValueChange={(v) => form.setValue("customerType", v as CustomerType)}>
                    <SelectTrigger id="customerType"><SelectValue placeholder="Select type" /></SelectTrigger>
                    <SelectContent>
                      {CUSTOMER_TYPES.map((t) => (<SelectItem key={t} value={t}>{CUSTOMER_TYPE_LABELS[t]}</SelectItem>))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="annualTurnover">Annual Turnover (₹)</Label>
                  <Input id="annualTurnover" type="number" placeholder="e.g. 75000000" {...form.register("annualTurnover")} />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="companyName">Company Name *</Label>
                  <Input id="companyName" placeholder="e.g. Acme Global Industries" {...form.register("companyName", { required: true })} />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="tradeName">Trade Name</Label>
                  <Input id="tradeName" placeholder="e.g. Acme Trading" {...form.register("tradeName")} />
                </div>
              </div>
            </fieldset>

            <Separator />

            {/* ── Addresses ── */}
            <fieldset className="space-y-5">
              <legend className="text-sm font-semibold">Addresses</legend>

              <AddressBlock
                title="Registered Address"
                prefix="registeredAddress"
                form={form}
              />

              <Separator className="my-2" />

              <AddressBlock
                title="Billing Address"
                prefix="billingAddress"
                form={form}
                disabled={billingSameAsRegistered}
                sameAsLabel="Same as Registered"
                sameAsChecked={billingSameAsRegistered}
                onSameAsChange={(checked) => {
                  form.setValue("billingSameAsRegistered", checked);
                  if (checked) {
                    const reg = form.getValues("registeredAddress");
                    form.setValue("billingAddress", { ...reg });
                    if (form.getValues("shippingSameAsBilling")) {
                      form.setValue("shippingAddress", { ...reg });
                    }
                  }
                }}
              />

              <Separator className="my-2" />

              <AddressBlock
                title="Shipping Address"
                prefix="shippingAddress"
                form={form}
                disabled={shippingSameAsBilling}
                sameAsLabel="Same as Billing"
                sameAsChecked={shippingSameAsBilling}
                onSameAsChange={(checked) => {
                  form.setValue("shippingSameAsBilling", checked);
                  if (checked) {
                    const bill = form.getValues("billingSameAsRegistered")
                      ? form.getValues("registeredAddress")
                      : form.getValues("billingAddress");
                    form.setValue("shippingAddress", { ...bill });
                  }
                }}
              />
            </fieldset>

            <Separator />

            {/* ── Payment Terms ── */}
            <fieldset className="space-y-4">
              <legend className="text-sm font-semibold">Agreed Payment Terms</legend>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="space-y-2">
                  <Label>Advance %</Label>
                  <Input type="number" placeholder="e.g. 50" {...form.register("paymentTerms.advancePercent")} />
                </div>
                <div className="space-y-2">
                  <Label>Before Dispatch %</Label>
                  <Input type="number" placeholder="e.g. 50" {...form.register("paymentTerms.beforeDispatchPercent")} />
                </div>
                <div className="space-y-2">
                  <Label>After Dispatch Days</Label>
                  <Input type="number" placeholder="e.g. 30" {...form.register("paymentTerms.afterDispatchDays")} />
                </div>
                <div className="space-y-2">
                  <Label>After Dispatch %</Label>
                  <Input type="number" placeholder="e.g. 0" {...form.register("paymentTerms.afterDispatchPercent")} />
                </div>
              </div>
            </fieldset>

            <Separator />

            {/* ── Points of Contact ── */}
            <fieldset className="space-y-4">
              <div className="flex items-center justify-between">
                <legend className="text-sm font-semibold">Points of Contact</legend>
                <Button type="button" variant="outline" size="sm" onClick={() => addPoc({ personName: "", designation: "", department: "", phone: "", email: "", primary: false })}>
                  <Plus className="size-3.5" /> Add
                </Button>
              </div>
              {pocFields.length === 0 && <p className="text-xs text-muted-foreground">No contacts added yet.</p>}
              {pocFields.map((field, idx) => (
                <div key={field.id} className="surface space-y-3.5 p-4 rounded-xl">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <p className="text-xs font-semibold text-muted-foreground">Contact {idx + 1}</p>
                      <label className="flex items-center gap-1.5 text-xs cursor-pointer">
                        <Checkbox
                          checked={form.watch(`pointOfContacts.${idx}.primary`)}
                          onCheckedChange={(v) => {
                            if (v === true) {
                              pocFields.forEach((_, i) => form.setValue(`pointOfContacts.${i}.primary`, false));
                            }
                            form.setValue(`pointOfContacts.${idx}.primary`, v === true);
                          }}
                        />
                        <span className={cn(form.watch(`pointOfContacts.${idx}.primary`) ? "text-primary font-medium" : "text-muted-foreground")}>Primary</span>
                      </label>
                    </div>
                    <Button type="button" variant="ghost" size="icon" className="size-7" onClick={() => removePoc(idx)}>
                      <Trash2 className="size-3.5 text-destructive" />
                    </Button>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                    <div className="space-y-1"><Label className="text-xs">Person Name *</Label><Input {...form.register(`pointOfContacts.${idx}.personName`, { required: true })} placeholder="Full name" /></div>
                    <div className="space-y-1"><Label className="text-xs">Designation</Label><Input {...form.register(`pointOfContacts.${idx}.designation`)} placeholder="e.g. Sales Ex." /></div>
                  </div>
                  <div className="space-y-1"><Label className="text-xs">Department</Label><Input {...form.register(`pointOfContacts.${idx}.department`)} placeholder="e.g. Sales, QA, QC, Admin" /></div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                    <div className="space-y-1"><Label className="text-xs">Phone</Label><Input {...form.register(`pointOfContacts.${idx}.phone`)} placeholder="+91-XXXXXXXXXX" /></div>
                    <div className="space-y-1"><Label className="text-xs">Email</Label><Input type="email" {...form.register(`pointOfContacts.${idx}.email`)} placeholder="email@example.com" /></div>
                  </div>
                </div>
              ))}
            </fieldset>
          </form>
        </div>

        {/* Fixed Footer at bottom */}
        <DialogFooter className="px-6 py-4 shrink-0 border-t border-border/40 bg-background flex flex-col-reverse sm:flex-row sm:justify-end gap-3">
          <Button type="button" variant="outline" className="w-full sm:w-auto" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button type="submit" form="client-form" disabled={isSubmitting} className="w-full sm:w-auto">
            {isSubmitting && <Loader2 className="size-4 animate-spin" />}
            {isEdit ? "Update Client" : "Create Client"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Admin Documents Panel ───────────────────────────────────────────────────

const DOC_LEFT: DocumentType[] = [
  "DRUG_LICENSE",
  "WHOLESALE_LICENSE",
  "WHO_GMP_COPY",
  "STATE_GMP_GLP_COPY",
  "NEUTRAL_CODE_CERTIFICATE",
  "LIST_OF_INTERNATIONAL_ACCREDITATION",
  "MSME_CERTIFICATE",
  "FIRM_REGISTRATION_CERTIFICATE",
];

const DOC_RIGHT: DocumentType[] = [
  "BANK_CHQ_LEAF",
  "IEC_CODE",
  "GST_RC_COPY",
  "PAN_CARD_COPY",
  "ADDRESS_PROOF_DOCS_COPY",
  "AADHAR_COPY",
  "CIN_COPY",
];

function formatBytes(bytes?: number): string {
  if (!bytes || bytes === 0) return "";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

function AdminDocumentsPanel({ client }: { client: Client }) {
  const queryClient = useQueryClient();
  const [uploadingDoc, setUploadingDoc] = useState<DocumentType | null>(null);
  const [viewingDoc, setViewingDoc] = useState<ClientDocument | null>(null);

  const docsMap = new Map<DocumentType, ClientDocument>();
  (client.documents ?? []).forEach((d) => {
    docsMap.set(d.documentType, d);
  });

  const uploadedCount = docsMap.size;
  const totalCount = DOC_LEFT.length + DOC_RIGHT.length;

  const deleteMutation = useMutation({
    mutationFn: (docId: string) => deleteDocument(client.id, docId),
    onSuccess: (updatedClient) => {
      queryClient.setQueryData<Client[]>(["clients"], (old = []) =>
        old.map((c) => (c.id === updatedClient.id ? updatedClient : c))
      );
      queryClient.invalidateQueries({ queryKey: ["clients"] });
      toast.success("Document removed");
    },
    onError: (err: Error) => toast.error(`Failed to delete document: ${err.message}`),
  });

  async function handleUpload(docType: DocumentType, file: File) {
    setUploadingDoc(docType);
    try {
      const updatedClient = await uploadDocument(client.id, file, docType);
      queryClient.setQueryData<Client[]>(["clients"], (old = []) =>
        old.map((c) => (c.id === updatedClient.id ? updatedClient : c))
      );
      queryClient.invalidateQueries({ queryKey: ["clients"] });
      toast.success(`${DOCUMENT_TYPE_LABELS[docType]} uploaded successfully`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to upload document";
      toast.error(`Failed to upload ${DOCUMENT_TYPE_LABELS[docType]}: ${msg}`);
    } finally {
      setUploadingDoc(null);
    }
  }

  return (
    <div className="space-y-6">
      {/* ── Summary Card ── */}
      <div className="surface p-4 flex items-center justify-between gap-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Document Dossier
          </p>
          <p className="text-sm font-medium mt-0.5">
            {uploadedCount} of {totalCount} documents attached
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant={uploadedCount === totalCount ? "default" : "secondary"}>
            {uploadedCount === totalCount ? "Complete" : `${Math.round((uploadedCount / totalCount) * 100)}% Complete`}
          </Badge>
        </div>
      </div>

      {/* ── Uploaded Documents List ── */}
      {client.documents && client.documents.length > 0 && (
        <div className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Uploaded Files ({client.documents.length})
          </p>
          <div className="space-y-2">
            {client.documents.map((doc) => {
              const label = DOCUMENT_TYPE_LABELS[doc.documentType] || doc.documentType;
              const filename = doc.originalFileName || doc.fileName || label;
              const downloadUrl = getDocumentDownloadUrl(client.id, doc.id || "");

              return (
                <div
                  key={doc.id || doc.documentType}
                  className="surface flex items-center justify-between p-3 gap-3"
                >
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary shrink-0">
                      <FileText className="size-4" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-semibold truncate leading-tight">
                          {label}
                        </p>
                        {doc.storageType && (
                          <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] font-mono text-muted-foreground shrink-0">
                            {doc.storageType}
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground truncate mt-0.5">
                        {filename} {doc.fileSize ? `• ${formatBytes(doc.fileSize)}` : ""}{" "}
                        {doc.uploadedAt ? `• ${new Date(doc.uploadedAt).toLocaleDateString()}` : ""}
                      </p>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1 shrink-0">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 gap-1.5 text-xs text-primary"
                      onClick={() => setViewingDoc(doc)}
                      title="View in document viewer"
                    >
                      <Eye className="size-3.5" />
                      View
                    </Button>

                    <a href={downloadUrl} download={filename} title="Download original file">
                      <Button variant="ghost" size="icon" className="size-8 text-muted-foreground">
                        <Download className="size-3.5" />
                      </Button>
                    </a>

                    <Button
                      variant="ghost"
                      size="icon"
                      className="size-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                      disabled={deleteMutation.isPending}
                      onClick={() => doc.id && deleteMutation.mutate(doc.id)}
                      title="Delete document"
                    >
                      <Trash2 className="size-3.5" />
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Document Upload Matrix ── */}
      <div className="space-y-3">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Document Checklist & Uploads
        </p>
        <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
          <div className="space-y-2">
            {DOC_LEFT.map((dt) => (
              <AdminDocRow
                key={dt}
                docType={dt}
                doc={docsMap.get(dt)}
                uploading={uploadingDoc === dt}
                onUpload={(f) => handleUpload(dt, f)}
                onView={(d) => setViewingDoc(d)}
              />
            ))}
          </div>
          <div className="space-y-2">
            {DOC_RIGHT.map((dt) => (
              <AdminDocRow
                key={dt}
                docType={dt}
                doc={docsMap.get(dt)}
                uploading={uploadingDoc === dt}
                onUpload={(f) => handleUpload(dt, f)}
                onView={(d) => setViewingDoc(d)}
              />
            ))}
          </div>
        </div>
      </div>

      {/* ── In-App Document Viewer Dialog ── */}
      <DocumentViewerDialog
        open={!!viewingDoc}
        onOpenChange={(o) => !o && setViewingDoc(null)}
        clientId={client.id}
        document={viewingDoc}
      />
    </div>
  );
}

function AdminDocRow({
  docType,
  doc,
  uploading,
  onUpload,
  onView,
}: {
  docType: DocumentType;
  doc?: ClientDocument;
  uploading: boolean;
  onUpload: (file: File) => void;
  onView: (doc: ClientDocument) => void;
}) {
  const inputRef = { current: null as HTMLInputElement | null };
  const uploaded = !!doc;

  return (
    <div
      className={cn(
        "flex items-center justify-between rounded-lg border px-3 py-2 text-xs transition-colors gap-2",
        uploaded ? "border-accent/30 bg-accent/5" : "border-border hover:bg-muted/40",
      )}
    >
      <span className={cn("truncate font-medium flex-1", uploaded && "text-accent")}>
        {DOCUMENT_TYPE_LABELS[docType]}
      </span>
      <input
        ref={(el) => { inputRef.current = el; }}
        type="file"
        className="hidden"
        accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
        onChange={(e) => {
          const file = e.target.files?.[0];
          if (file) { onUpload(file); e.target.value = ""; }
        }}
      />
      <div className="flex items-center gap-1 shrink-0">
        {uploaded && (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="h-6 text-[11px] px-2 text-accent hover:text-accent font-medium gap-1"
            onClick={() => onView(doc)}
          >
            <Eye className="size-3" />
            View
          </Button>
        )}
        <Button
          type="button"
          variant={uploaded ? "ghost" : "outline"}
          size="sm"
          className={cn("h-6 shrink-0 text-[11px] px-2", uploaded && "text-muted-foreground")}
          disabled={uploading}
          onClick={() => inputRef.current?.click()}
          title={uploaded ? "Replace file" : "Upload file"}
        >
          {uploading ? (
            <Loader2 className="size-3 animate-spin" />
          ) : (
            <Upload className="size-3" />
          )}
          {uploaded ? "Replace" : "Upload"}
        </Button>
      </div>
    </div>
  );
}