/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellClientsRouteImport } from './routes/_shell.clients'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellInquiryRouteImport } from './routes/_shell.inquiry'
import { Route as ShellOrdersRouteImport } from './routes/_shell.orders'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUserManagementRouteImport } from './routes/_shell.user-management'
import { Route as IndexLoginRouteImport } from './routes/index/login'
import { Route as RegisterClientIdRouteImport } from './routes/register-client/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInquiryRoute = ShellInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersRoute = ShellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUserManagementRoute = ShellUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => ShellRoute,
} as any)
const IndexLoginRoute = IndexLoginRouteImport.update({
  id: '/index/login',
  path: '/index/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterClientIdRoute = RegisterClientIdRouteImport.update({
  id: '/register-client/$id',
  path: '/register-client/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/orders': typeof ShellOrdersRoute
  '/products': typeof ShellProductsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/orders': typeof ShellOrdersRoute
  '/products': typeof ShellProductsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/inquiry': typeof ShellInquiryRoute
  '/_shell/orders': typeof ShellOrdersRoute
  '/_shell/products': typeof ShellProductsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/inquiry'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/index/login'
    | '/register-client/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/inquiry'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/index/login'
    | '/register-client/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/clients'
    | '/_shell/dashboard'
    | '/_shell/inquiry'
    | '/_shell/orders'
    | '/_shell/products'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/user-management'
    | '/index/login'
    | '/register-client/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  IndexLoginRoute: typeof IndexLoginRoute
  RegisterClientIdRoute: typeof RegisterClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inquiry': {
      id: '/_shell/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof ShellInquiryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders': {
      id: '/_shell/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShellOrdersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/user-management': {
      id: '/_shell/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof ShellUserManagementRouteImport
      parentRoute: typeof ShellRoute
    }
    '/index/login': {
      id: '/index/login'
      path: '/index/login'
      fullPath: '/index/login'
      preLoaderRoute: typeof IndexLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-client/$id': {
      id: '/register-client/$id'
      path: '/register-client/$id'
      fullPath: '/register-client/$id'
      preLoaderRoute: typeof RegisterClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellClientsRoute: typeof ShellClientsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellInquiryRoute: typeof ShellInquiryRoute
  ShellOrdersRoute: typeof ShellOrdersRoute
  ShellProductsRoute: typeof ShellProductsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUserManagementRoute: typeof ShellUserManagementRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClientsRoute: ShellClientsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellInquiryRoute: ShellInquiryRoute,
  ShellOrdersRoute: ShellOrdersRoute,
  ShellProductsRoute: ShellProductsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUserManagementRoute: ShellUserManagementRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  IndexLoginRoute: IndexLoginRoute,
  RegisterClientIdRoute: RegisterClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
