/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellClientsRouteImport } from './routes/_shell.clients'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellInquiryRouteImport } from './routes/_shell.inquiry'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInquiryRoute = ShellInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/products': typeof ShellProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/products': typeof ShellProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/inquiry': typeof ShellInquiryRoute
  '/_shell/products': typeof ShellProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clients' | '/dashboard' | '/inquiry' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clients' | '/dashboard' | '/inquiry' | '/products'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/clients'
    | '/_shell/dashboard'
    | '/_shell/inquiry'
    | '/_shell/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inquiry': {
      id: '/_shell/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof ShellInquiryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellClientsRoute: typeof ShellClientsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellInquiryRoute: typeof ShellInquiryRoute
  ShellProductsRoute: typeof ShellProductsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClientsRoute: ShellClientsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellInquiryRoute: ShellInquiryRoute,
  ShellProductsRoute: ShellProductsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
