/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellClientsRouteImport } from './routes/_shell.clients'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellInquiryRouteImport } from './routes/_shell.inquiry'
import { Route as ShellOrdersRouteImport } from './routes/_shell.orders'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUserManagementRouteImport } from './routes/_shell.user-management'
import { Route as IndexLoginRouteImport } from './routes/index/login'
import { Route as RegisterClientIdRouteImport } from './routes/register-client/$id'
import { Route as ShellClientsClientIdRouteImport } from './routes/_shell.clients_.$clientId'
import { Route as ShellInquiryInquiryIdRouteImport } from './routes/_shell.inquiry_.$inquiryId'
import { Route as ShellProductsProductIdRouteImport } from './routes/_shell.products_.$productId'
import { Route as ShellClientsClientIdEditRouteImport } from './routes/_shell.clients_.$clientId.edit'
import { Route as ShellInquiryInquiryIdEditRouteImport } from './routes/_shell.inquiry_.$inquiryId.edit'
import { Route as ShellProductsProductIdEditRouteImport } from './routes/_shell.products_.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInquiryRoute = ShellInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersRoute = ShellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUserManagementRoute = ShellUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => ShellRoute,
} as any)
const IndexLoginRoute = IndexLoginRouteImport.update({
  id: '/index/login',
  path: '/index/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterClientIdRoute = RegisterClientIdRouteImport.update({
  id: '/register-client/$id',
  path: '/register-client/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClientsClientIdRoute = ShellClientsClientIdRouteImport.update({
  id: '/clients_/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInquiryInquiryIdRoute = ShellInquiryInquiryIdRouteImport.update({
  id: '/inquiry_/$inquiryId',
  path: '/inquiry/$inquiryId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsProductIdRoute = ShellProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsClientIdEditRoute =
  ShellClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ShellClientsClientIdRoute,
  } as any)
const ShellInquiryInquiryIdEditRoute =
  ShellInquiryInquiryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ShellInquiryInquiryIdRoute,
  } as any)
const ShellProductsProductIdEditRoute =
  ShellProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ShellProductsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/orders': typeof ShellOrdersRoute
  '/products': typeof ShellProductsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
  '/clients/$clientId': typeof ShellClientsClientIdRouteWithChildren
  '/inquiry/$inquiryId': typeof ShellInquiryInquiryIdRouteWithChildren
  '/products/$productId': typeof ShellProductsProductIdRouteWithChildren
  '/clients/$clientId/edit': typeof ShellClientsClientIdEditRoute
  '/inquiry/$inquiryId/edit': typeof ShellInquiryInquiryIdEditRoute
  '/products/$productId/edit': typeof ShellProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ShellClientsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inquiry': typeof ShellInquiryRoute
  '/orders': typeof ShellOrdersRoute
  '/products': typeof ShellProductsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
  '/clients/$clientId': typeof ShellClientsClientIdRouteWithChildren
  '/inquiry/$inquiryId': typeof ShellInquiryInquiryIdRouteWithChildren
  '/products/$productId': typeof ShellProductsProductIdRouteWithChildren
  '/clients/$clientId/edit': typeof ShellClientsClientIdEditRoute
  '/inquiry/$inquiryId/edit': typeof ShellInquiryInquiryIdEditRoute
  '/products/$productId/edit': typeof ShellProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/inquiry': typeof ShellInquiryRoute
  '/_shell/orders': typeof ShellOrdersRoute
  '/_shell/products': typeof ShellProductsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/user-management': typeof ShellUserManagementRoute
  '/index/login': typeof IndexLoginRoute
  '/register-client/$id': typeof RegisterClientIdRoute
  '/_shell/clients_/$clientId': typeof ShellClientsClientIdRouteWithChildren
  '/_shell/inquiry_/$inquiryId': typeof ShellInquiryInquiryIdRouteWithChildren
  '/_shell/products_/$productId': typeof ShellProductsProductIdRouteWithChildren
  '/_shell/clients_/$clientId/edit': typeof ShellClientsClientIdEditRoute
  '/_shell/inquiry_/$inquiryId/edit': typeof ShellInquiryInquiryIdEditRoute
  '/_shell/products_/$productId/edit': typeof ShellProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/inquiry'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/index/login'
    | '/register-client/$id'
    | '/clients/$clientId'
    | '/inquiry/$inquiryId'
    | '/products/$productId'
    | '/clients/$clientId/edit'
    | '/inquiry/$inquiryId/edit'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/inquiry'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/index/login'
    | '/register-client/$id'
    | '/clients/$clientId'
    | '/inquiry/$inquiryId'
    | '/products/$productId'
    | '/clients/$clientId/edit'
    | '/inquiry/$inquiryId/edit'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/clients'
    | '/_shell/dashboard'
    | '/_shell/inquiry'
    | '/_shell/orders'
    | '/_shell/products'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/user-management'
    | '/index/login'
    | '/register-client/$id'
    | '/_shell/clients_/$clientId'
    | '/_shell/inquiry_/$inquiryId'
    | '/_shell/products_/$productId'
    | '/_shell/clients_/$clientId/edit'
    | '/_shell/inquiry_/$inquiryId/edit'
    | '/_shell/products_/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  IndexLoginRoute: typeof IndexLoginRoute
  RegisterClientIdRoute: typeof RegisterClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inquiry': {
      id: '/_shell/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof ShellInquiryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders': {
      id: '/_shell/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShellOrdersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/user-management': {
      id: '/_shell/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof ShellUserManagementRouteImport
      parentRoute: typeof ShellRoute
    }
    '/index/login': {
      id: '/index/login'
      path: '/index/login'
      fullPath: '/index/login'
      preLoaderRoute: typeof IndexLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-client/$id': {
      id: '/register-client/$id'
      path: '/register-client/$id'
      fullPath: '/register-client/$id'
      preLoaderRoute: typeof RegisterClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/clients_/$clientId': {
      id: '/_shell/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ShellClientsClientIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inquiry_/$inquiryId': {
      id: '/_shell/inquiry_/$inquiryId'
      path: '/inquiry/$inquiryId'
      fullPath: '/inquiry/$inquiryId'
      preLoaderRoute: typeof ShellInquiryInquiryIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products_/$productId': {
      id: '/_shell/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ShellProductsProductIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients_/$clientId/edit': {
      id: '/_shell/clients_/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof ShellClientsClientIdEditRouteImport
      parentRoute: typeof ShellClientsClientIdRoute
    }
    '/_shell/inquiry_/$inquiryId/edit': {
      id: '/_shell/inquiry_/$inquiryId/edit'
      path: '/edit'
      fullPath: '/inquiry/$inquiryId/edit'
      preLoaderRoute: typeof ShellInquiryInquiryIdEditRouteImport
      parentRoute: typeof ShellInquiryInquiryIdRoute
    }
    '/_shell/products_/$productId/edit': {
      id: '/_shell/products_/$productId/edit'
      path: '/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ShellProductsProductIdEditRouteImport
      parentRoute: typeof ShellProductsProductIdRoute
    }
  }
}

interface ShellClientsClientIdRouteChildren {
  ShellClientsClientIdEditRoute: typeof ShellClientsClientIdEditRoute
}

const ShellClientsClientIdRouteChildren: ShellClientsClientIdRouteChildren = {
  ShellClientsClientIdEditRoute: ShellClientsClientIdEditRoute,
}

const ShellClientsClientIdRouteWithChildren =
  ShellClientsClientIdRoute._addFileChildren(ShellClientsClientIdRouteChildren)

interface ShellInquiryInquiryIdRouteChildren {
  ShellInquiryInquiryIdEditRoute: typeof ShellInquiryInquiryIdEditRoute
}

const ShellInquiryInquiryIdRouteChildren: ShellInquiryInquiryIdRouteChildren = {
  ShellInquiryInquiryIdEditRoute: ShellInquiryInquiryIdEditRoute,
}

const ShellInquiryInquiryIdRouteWithChildren =
  ShellInquiryInquiryIdRoute._addFileChildren(
    ShellInquiryInquiryIdRouteChildren,
  )

interface ShellProductsProductIdRouteChildren {
  ShellProductsProductIdEditRoute: typeof ShellProductsProductIdEditRoute
}

const ShellProductsProductIdRouteChildren: ShellProductsProductIdRouteChildren =
  {
    ShellProductsProductIdEditRoute: ShellProductsProductIdEditRoute,
  }

const ShellProductsProductIdRouteWithChildren =
  ShellProductsProductIdRoute._addFileChildren(
    ShellProductsProductIdRouteChildren,
  )

interface ShellRouteChildren {
  ShellClientsRoute: typeof ShellClientsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellInquiryRoute: typeof ShellInquiryRoute
  ShellOrdersRoute: typeof ShellOrdersRoute
  ShellProductsRoute: typeof ShellProductsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUserManagementRoute: typeof ShellUserManagementRoute
  ShellClientsClientIdRoute: typeof ShellClientsClientIdRouteWithChildren
  ShellInquiryInquiryIdRoute: typeof ShellInquiryInquiryIdRouteWithChildren
  ShellProductsProductIdRoute: typeof ShellProductsProductIdRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClientsRoute: ShellClientsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellInquiryRoute: ShellInquiryRoute,
  ShellOrdersRoute: ShellOrdersRoute,
  ShellProductsRoute: ShellProductsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUserManagementRoute: ShellUserManagementRoute,
  ShellClientsClientIdRoute: ShellClientsClientIdRouteWithChildren,
  ShellInquiryInquiryIdRoute: ShellInquiryInquiryIdRouteWithChildren,
  ShellProductsProductIdRoute: ShellProductsProductIdRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  IndexLoginRoute: IndexLoginRoute,
  RegisterClientIdRoute: RegisterClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
